"""Generate the `derp.toml` + `infra/{dev,prod}/` tree from `InfraChoices`.

The generator is dependency-light: it composes plain strings from
:mod:`derp.cli.scaffolding.infra.specs`, with Jinja2 used only for the
per-file Terraform templates (multi-line, conditional, easier to read as
templates than as Python string-builds).
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from pathlib import Path

import jinja2

from derp.cli.scaffolding.infra.specs import (
    ALWAYS_EMITTED_ENV_VARS,
    VENDOR_CREDENTIALS,
    WELL_LIT_SERVICES,
    InfraChoices,
    ServiceMode,
    ServiceSpec,
    TfVariable,
    service_spec,
)

# Module pin pulled into rendered Terraform. Bump deliberately when the
# `derp-infra` module's contract changes.
DERP_INFRA_MODULE_SOURCE = "derp/derp/aws"
DERP_INFRA_MODULE_VERSION = "~> 0.1"

# Required Terraform + provider versions, pinned in `infra/versions.tf`.
TERRAFORM_REQUIRED_VERSION = ">= 1.5"
PROVIDER_VERSIONS = {
    "vercel": "~> 1.0",
    "cloudflare": "~> 5.0",
    "stripe": "~> 1.0",
    "planetscale": "~> 0.5",
    "workos": "~> 0.1",
}

GITIGNORE_LINES = (
    "infra/**/terraform.tfvars",
    "infra/**/.terraform/",
    "infra/**/.terraform.lock.hcl",
    "infra/**/*.tfstate",
    "infra/**/*.tfstate.*",
    ".env",
    ".env.dev",
    ".env.prod",
)


@dataclass(frozen=True)
class InfraLayout:
    """Resolved layout for one environment, derived from `InfraChoices`."""

    env: str  # "dev" or "prod"
    tier: str  # "hobby" or "production"
    choices: InfraChoices

    def vendor_credentials(self) -> list[TfVariable]:
        """All vendor provisioning credentials needed for this env."""
        result: list[TfVariable] = []
        seen: set[str] = set()
        for vendor in sorted(self.choices.vendors_in_use(), key=lambda v: v.value):
            for cred in VENDOR_CREDENTIALS.get(vendor, ()):
                if cred.name not in seen:
                    result.append(cred)
                    seen.add(cred.name)
        return result

    def import_variables(self) -> list[tuple[ServiceSpec, str, str]]:
        """(spec, var_name, example) for each Import-mode resource ID."""
        result: list[tuple[ServiceSpec, str, str]] = []
        for choice in self.choices.modes:
            if choice.mode != ServiceMode.IMPORT:
                continue
            spec = service_spec(choice.service)
            for imp in spec.import_resources:
                result.append((spec, imp.var_name, imp.example))
        return result

    def byo_variables(self) -> list[tuple[ServiceSpec, str, str, str]]:
        """(spec, var_name, env_var, example) for each BYO credential."""
        result: list[tuple[ServiceSpec, str, str, str]] = []
        for choice in self.choices.modes:
            if choice.mode != ServiceMode.BYO:
                continue
            spec = service_spec(choice.service)
            for byo in spec.byo_credentials:
                result.append((spec, byo.var_name, byo.env_var, byo.example))
        return result

    def env_vars_emitted(self) -> list[str]:
        """All env var names the env_vars output is expected to contain."""
        emitted: list[str] = list(ALWAYS_EMITTED_ENV_VARS)
        for spec in self.choices.enabled_services():
            emitted.extend(spec.env_vars)
        return emitted


def _env() -> jinja2.Environment:
    loader = jinja2.PackageLoader(
        "derp.cli.scaffolding.infra", package_path="templates"
    )
    env = jinja2.Environment(
        loader=loader,
        undefined=jinja2.StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    return env


def render_derp_toml(choices: InfraChoices) -> str:
    """Render the `derp.toml` content for the chosen services.

    Only enabled services (mode != Skip) get sections. Always-on database
    section appears first because every derp app needs one.
    """
    sections: list[str] = []
    # Database first if enabled, otherwise the user is on their own.
    enabled = choices.enabled_services()
    # Preserve well-lit-path order (DB first per WELL_LIT_SERVICES ordering).
    for spec in WELL_LIT_SERVICES:
        if spec not in enabled:
            continue
        sections.append(spec.toml_section.rstrip())
    # Vercel Queues (always provisioned) gets a [queue.vercel] section.
    sections.append(
        "[queue.vercel]\n"
        'api_token = "$VERCEL_QUEUE_TOKEN"\n'
        'project_id = "$VERCEL_PROJECT_ID"\n'
        'default_queue = "$VERCEL_QUEUE_DEFAULT"\n'.rstrip()
    )
    header = (
        f"# derp.toml — generated by `derp init --infra` for {choices.app_name}\n"
        "# Env vars (e.g. $WORKOS_API_KEY) are populated by\n"
        "# `derp env pull <env>` after `terraform apply`.\n"
    )
    return header + "\n" + "\n\n".join(sections) + "\n"


def _render_template(name: str, **kwargs: object) -> str:
    return _env().get_template(name).render(**kwargs)


def render_versions_tf(choices: InfraChoices | None = None) -> str:
    """Render `infra/versions.tf` with only the providers actually in use.

    `versions.tf` is shared across dev and prod, so it must cover the union
    of providers needed across both. Since dev/prod always share the same
    mode shape (only credentials differ), the union is simply the providers
    Terraform needs to talk to in this scaffold — derived from
    `choices.vendors_in_use()`. With `choices=None` (legacy), every
    well-lit-path provider is emitted.
    """
    if choices is None:
        names = list(PROVIDER_VERSIONS)
    else:
        # Map our Vendor enum values to the provider names in PROVIDER_VERSIONS.
        # They line up 1:1 today; keeping this indirection makes future
        # divergence (e.g. an Upstash provider) explicit.
        names = sorted(
            v.value for v in choices.vendors_in_use() if v.value in PROVIDER_VERSIONS
        )
    pinned = {name: PROVIDER_VERSIONS[name] for name in names}
    return _render_template(
        "versions.tf.j2",
        terraform_required_version=TERRAFORM_REQUIRED_VERSION,
        provider_versions=pinned,
    )


def render_main_tf(layout: InfraLayout) -> str:
    return _render_template(
        "main.tf.j2",
        layout=layout,
        well_lit_services=WELL_LIT_SERVICES,
        ServiceMode=ServiceMode,
        module_source=DERP_INFRA_MODULE_SOURCE,
        module_version=DERP_INFRA_MODULE_VERSION,
    )


def render_variables_tf(layout: InfraLayout) -> str:
    return _render_template(
        "variables.tf.j2",
        layout=layout,
    )


def render_outputs_tf() -> str:
    return _render_template("outputs.tf.j2")


def render_backend_tf(layout: InfraLayout) -> str:
    return _render_template("backend.tf.j2", layout=layout)


def render_tfvars_example(layout: InfraLayout) -> str:
    return _render_template("terraform.tfvars.example.j2", layout=layout)


def render_infra_readme(choices: InfraChoices) -> str:
    return _render_template("README.md.j2", choices=choices)


def _write(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def _ensure_gitignore(project_root: Path) -> None:
    gitignore = project_root / ".gitignore"
    existing = gitignore.read_text() if gitignore.exists() else ""
    additions: list[str] = []
    for line in GITIGNORE_LINES:
        if line not in existing:
            additions.append(line)
    if not additions:
        return
    sep = "" if existing.endswith("\n") or not existing else "\n"
    block = "\n# Added by `derp init --infra`\n" + "\n".join(additions) + "\n"
    gitignore.write_text(
        existing + sep + block.lstrip("\n") if existing else block.lstrip("\n")
    )


def generate_infra_scaffold(
    project_root: Path,
    choices: InfraChoices,
    *,
    force: bool = False,
    write_derp_toml: bool = True,
) -> list[Path]:
    """Write the `derp.toml` + `infra/{dev,prod}/` tree under `project_root`.

    Returns the list of files written. Raises FileExistsError if any file
    already exists and `force` is False.
    """
    written: list[Path] = []

    if write_derp_toml:
        derp_toml = project_root / "derp.toml"
        _write(derp_toml, render_derp_toml(choices), force=force)
        written.append(derp_toml)

    infra_dir = project_root / "infra"

    versions = infra_dir / "versions.tf"
    _write(versions, render_versions_tf(choices), force=force)
    written.append(versions)

    readme = infra_dir / "README.md"
    _write(readme, render_infra_readme(choices), force=force)
    written.append(readme)

    for env, tier in (("dev", "hobby"), ("prod", "production")):
        layout = InfraLayout(env=env, tier=tier, choices=choices)
        env_dir = infra_dir / env

        files: dict[str, str] = {
            "main.tf": render_main_tf(layout),
            "variables.tf": render_variables_tf(layout),
            "outputs.tf": render_outputs_tf(),
            "backend.tf": render_backend_tf(layout),
            "terraform.tfvars.example": render_tfvars_example(layout),
        }
        for name, content in files.items():
            path = env_dir / name
            _write(path, content, force=force)
            written.append(path)

    _ensure_gitignore(project_root)

    return written


def package_template_paths() -> list[str]:
    """List packaged template filenames (for tests)."""
    root = resources.files("derp.cli.scaffolding.infra").joinpath("templates")
    return sorted(p.name for p in root.iterdir() if p.is_file())
