# main.tf — well-lit path Terraform module wiring for dev.
# Generated by `derp init --infra`. Safe to edit; rerun `derp env pull dev`
# after `terraform apply` to sync outputs into `.env.dev`.

module "derp" {
  source  = "derp/derp/aws"
  version = "~> 0.1"

  app_name    = "demo-app"
  environment = "dev"
  tier        = "hobby"
  region      = "us-east"

  # Vendor provisioning credentials (used by Terraform itself, not relayed to derp).
  cloudflare_api_token = var.cloudflare_api_token
  cloudflare_account_id = var.cloudflare_account_id
  planetscale_service_token_id = var.planetscale_service_token_id
  planetscale_service_token = var.planetscale_service_token
  planetscale_organization = var.planetscale_organization
  stripe_api_key = var.stripe_api_key
  vercel_api_token = var.vercel_api_token
  vercel_team_id = var.vercel_team_id
  workos_management_token = var.workos_management_token

  # Per-service mode + inputs.
  mode_db = "provision"

  mode_auth = "provision"

  mode_storage = "provision"

  mode_kv = "provision"

  mode_payments = "provision"

  mode_ai = "provision"

  mode_email = "byo"
  byo_resend_api_key = var.byo_resend_api_key
  byo_resend_from_email = var.byo_resend_from_email

}

# TF 1.5+ declarative imports — adopt existing resources into Terraform state
# on the next `terraform apply`. Safe to leave even after import completes;
# Terraform tracks the import and won't re-import the same resource.
# (no Import-mode services in this environment)
