"""`derp env` subcommand group.

Currently exposes `derp env pull <env>` for syncing terraform outputs into a
local `.env.<env>` file. Modeled on `vercel env pull`. Scales to `push`,
`list`, `diff` later without renaming.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Annotated

import typer

env_app = typer.Typer(
    name="env",
    help="Sync env vars between Terraform outputs and local .env files.",
    no_args_is_help=True,
)


_VALID_ENVS = ("dev", "prod")


def _shell_quote(value: str) -> str:
    """Quote a value for use in a `.env` file.

    `.env` parsers vary in what they tolerate. Use double quotes and escape
    `"` and `\\` — this matches python-dotenv's parsing.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _run_terraform_output(infra_env_dir: Path) -> dict[str, object]:
    """Run `terraform output -json` and parse the result.

    Returns the contents of the top-level `env_vars` value, which is a map
    of env-var-name → string.
    """
    try:
        completed = subprocess.run(
            ["terraform", "output", "-json", "env_vars"],
            cwd=str(infra_env_dir),
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise typer.BadParameter(
            "`terraform` binary not found on PATH. Install Terraform "
            "(or OpenTofu) and retry."
        ) from exc
    except subprocess.CalledProcessError as exc:
        stderr = (exc.stderr or "").strip()
        raise typer.BadParameter(
            f"`terraform output` failed in {infra_env_dir}:\n{stderr}\n"
            "Did you run `terraform init && terraform apply` in that directory?"
        ) from exc

    try:
        # `terraform output -json env_vars` returns the value directly
        # (because we asked for one specific output), so it's already the
        # env_vars map — not wrapped in another `{"env_vars": {...}}`.
        data = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise typer.BadParameter(
            f"`terraform output` returned non-JSON output:\n{completed.stdout}"
        ) from exc

    if not isinstance(data, dict):
        raise typer.BadParameter(
            "Expected `env_vars` output to be a map of string → string, "
            f"got: {type(data).__name__}"
        )
    return data


def _format_env_file(values: dict[str, object]) -> str:
    """Render a sorted-by-key `.env` file from a name → value map."""
    lines: list[str] = [
        "# Generated by `derp env pull`. Do not edit by hand — rerun to refresh.",
        "",
    ]
    for key in sorted(values):
        value = values[key]
        if not isinstance(value, str):
            value = json.dumps(value)
        lines.append(f"{key}={_shell_quote(value)}")
    lines.append("")
    return "\n".join(lines)


@env_app.command("pull")
def pull(
    env: Annotated[
        str,
        typer.Argument(
            help="Environment to pull (`dev` or `prod`). Matches `infra/<env>/`.",
        ),
    ],
    force: Annotated[
        bool,
        typer.Option(
            "--force",
            "-f",
            help="Overwrite an existing `.env.prod` without prompting.",
        ),
    ] = False,
    stdout: Annotated[
        bool,
        typer.Option(
            "--stdout",
            help="Print to stdout instead of writing `.env.<env>`.",
        ),
    ] = False,
    infra_dir: Annotated[
        Path,
        typer.Option(
            "--infra-dir",
            help="Root infra directory (containing `<env>/`). Defaults to `./infra`.",
        ),
    ] = Path("infra"),
) -> None:
    """Pull Terraform outputs into a local `.env.<env>` file.

    Reads `terraform output -json env_vars` from `infra/<env>/` and writes the
    result to `.env.<env>` (or stdout). The framework reads those env vars
    via the `$VAR_NAME` references in `derp.toml`.
    """
    if env not in _VALID_ENVS:
        raise typer.BadParameter(
            f"env must be one of {_VALID_ENVS!r}, got {env!r}",
            param_hint="env",
        )

    env_dir = infra_dir / env
    if not env_dir.is_dir():
        raise typer.BadParameter(
            f"{env_dir} does not exist. Run `derp init --infra` to scaffold it."
        )

    values = _run_terraform_output(env_dir)
    rendered = _format_env_file(values)

    if stdout:
        typer.echo(rendered, nl=False)
        return

    out_path = Path(f".env.{env}")
    if env == "prod" and out_path.exists() and not force:
        raise typer.BadParameter(
            f"{out_path} already exists. Re-run with --force to overwrite.",
        )
    out_path.write_text(rendered)
    typer.echo(f"Wrote {out_path} ({len(values)} variables)")
