# versions.tf — pinned Terraform + provider versions, shared by dev/prod.
# Generated by `derp init --infra`. Bump deliberately when upstream providers
# release breaking changes; rerun `terraform init -upgrade` in each env dir.

terraform {
  required_version = ">= 1.5"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
    planetscale = {
      source  = "planetscale/planetscale"
      version = "~> 0.5"
    }
    stripe = {
      source  = "stripe/stripe"
      version = "~> 1.0"
    }
    vercel = {
      source  = "vercel/vercel"
      version = "~> 1.0"
    }
    workos = {
      source  = "workos/workos"
      version = "~> 0.1"
    }
  }
}
