"""Derp chorm — A strongly-typed async Python ORM for ClickHouse.

Example usage::

    from derp.chorm import (
        Table, UInt64, String, DateTime, LowCardinality, Field, Fn,
        MergeTree, ClickHouseEngine,
    )

    class Event(Table, table="events"):
        id: UInt64 = Field()
        user_id: UInt64 = Field()
        ts: DateTime = Field(default=Fn.now())
        type: LowCardinality[String] = Field()
        __engine__ = MergeTree(order_by=("user_id", "ts"))

    async with ClickHouseEngine(host="localhost") as db:
        await db.create_table(Event, if_not_exists=True)
        await db.insert(Event).values(
            id=1, user_id=42, type="click",
        ).execute()
        rows = await (
            db.select(Event)
              .where(Event.user_id == 42)
              .order_by(Event.ts, desc=True)
              .limit(100)
              .execute()
        )
"""

from derp.chorm.column.base import (
    Alias as ColumnAlias,
)
from derp.chorm.column.base import (
    Codec,
    Column,
    Ephemeral,
    Field,
    FieldSpec,
    Fn,
    Materialized,
)
from derp.chorm.column.types import (
    JSON,
    UUID,
    AggregateFunction,
    Array,
    Bool,
    Date,
    Date32,
    DateTime,
    DateTime64,
    Decimal,
    Decimal32,
    Decimal64,
    Decimal128,
    Decimal256,
    Dynamic,
    Enum8,
    Enum16,
    FixedString,
    Float32,
    Float64,
    Int8,
    Int16,
    Int32,
    Int64,
    Int128,
    Int256,
    IPv4,
    IPv6,
    LowCardinality,
    Map,
    MultiPolygon,
    Nested,
    Nothing,
    Nullable,
    Point,
    Polygon,
    Ring,
    SimpleAggregateFunction,
    String,
    Tuple,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    UInt128,
    UInt256,
    Variant,
)
from derp.chorm.ddl import (
    build_create_database,
    build_create_dictionary,
    build_create_materialized_view,
    build_create_table,
    build_create_view,
    build_drop_database,
    build_drop_table,
    build_exchange_tables,
    build_optimize_table,
    build_rename_table,
    build_truncate_table,
)
from derp.chorm.engine import ClickHouseEngine
from derp.chorm.engines import (
    HDFS,
    JDBC,
    ODBC,
    S3,
    URL,
    AggregatingMergeTree,
    Buffer,
    CollapsingMergeTree,
    Dictionary,
    Distributed,
    File,
    GraphiteMergeTree,
    Join,
    KafkaEngine,
    Log,
    MaterializedView,
    Memory,
    Merge,
    MergeTree,
    MySQL,
    Null,
    PostgreSQL,
    ReplacingMergeTree,
    ReplicatedAggregatingMergeTree,
    ReplicatedCollapsingMergeTree,
    ReplicatedGraphiteMergeTree,
    ReplicatedMergeTree,
    ReplicatedReplacingMergeTree,
    ReplicatedSummingMergeTree,
    ReplicatedVersionedCollapsingMergeTree,
    SetEngine,
    StripeLog,
    SummingMergeTree,
    TableEngine,
    TinyLog,
    VersionedCollapsingMergeTree,
    View,
)
from derp.chorm.exceptions import (
    ChormBackendError,
    ChormError,
    ChormNotConnectedError,
    NoRowsError,
)
from derp.chorm.expression_base import (
    ComparisonOperator,
    Expression,
    LogicalOperator,
    Params,
)
from derp.chorm.index import Index, IndexType, Projection
from derp.chorm.query import (
    AlterQuery,
    DeleteMutation,
    InsertQuery,
    JoinStrictness,
    JoinType,
    OrderDirection,
    SelectQuery,
    UpdateMutation,
    f,
    lit,
    raw,
    sql,
)
from derp.chorm.query.expressions import to_expr
from derp.chorm.query.functions import (
    abs_,
    array,
    array_join,
    cast,
    coalesce,
    concat,
    date_add,
    date_diff,
    hash64,
    if_,
    ifnull,
    length,
    lower,
    map_,
    over,
    position,
    regex_replace,
    replace_all,
    round_,
    substring,
    to_date,
    to_datetime,
    to_start_of_day,
    to_start_of_hour,
    to_start_of_minute,
    to_start_of_month,
    to_yyyymm,
    to_yyyymmdd,
    tuple_,
    upper,
)
from derp.chorm.table import Table

__version__ = "0.1.0"

__all__ = [
    # Engine
    "ClickHouseEngine",
    # Exceptions
    "ChormError",
    "ChormNotConnectedError",
    "ChormBackendError",
    "NoRowsError",
    # Table & column descriptors
    "Table",
    "Column",
    "Field",
    "FieldSpec",
    "Codec",
    "Fn",
    "Materialized",
    "ColumnAlias",
    "Ephemeral",
    # Integer types
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "UInt128",
    "UInt256",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "Int128",
    "Int256",
    # Float types
    "Float32",
    "Float64",
    # Decimal types
    "Decimal",
    "Decimal32",
    "Decimal64",
    "Decimal128",
    "Decimal256",
    # Bool
    "Bool",
    # String types
    "String",
    "FixedString",
    # Temporal types
    "Date",
    "Date32",
    "DateTime",
    "DateTime64",
    # UUID
    "UUID",
    # IP
    "IPv4",
    "IPv6",
    # Enum
    "Enum8",
    "Enum16",
    # JSON / dynamic
    "JSON",
    "Dynamic",
    "Nothing",
    # Wrappers
    "LowCardinality",
    "Nullable",
    # Composites
    "Array",
    "Tuple",
    "Map",
    "Nested",
    "Variant",
    # Aggregate state
    "AggregateFunction",
    "SimpleAggregateFunction",
    # Geo
    "Point",
    "Ring",
    "Polygon",
    "MultiPolygon",
    # Engines
    "TableEngine",
    "MergeTree",
    "ReplacingMergeTree",
    "SummingMergeTree",
    "AggregatingMergeTree",
    "CollapsingMergeTree",
    "VersionedCollapsingMergeTree",
    "GraphiteMergeTree",
    "ReplicatedMergeTree",
    "ReplicatedReplacingMergeTree",
    "ReplicatedSummingMergeTree",
    "ReplicatedAggregatingMergeTree",
    "ReplicatedCollapsingMergeTree",
    "ReplicatedVersionedCollapsingMergeTree",
    "ReplicatedGraphiteMergeTree",
    "Log",
    "TinyLog",
    "StripeLog",
    "Memory",
    "Null",
    "Buffer",
    "Distributed",
    "Merge",
    "Dictionary",
    "Join",
    "SetEngine",
    "URL",
    "File",
    "View",
    "MaterializedView",
    "KafkaEngine",
    "S3",
    "HDFS",
    "MySQL",
    "PostgreSQL",
    "ODBC",
    "JDBC",
    # Query builders
    "SelectQuery",
    "InsertQuery",
    "AlterQuery",
    "UpdateMutation",
    "DeleteMutation",
    "JoinType",
    "JoinStrictness",
    "OrderDirection",
    # Expression base
    "Expression",
    "Params",
    "ComparisonOperator",
    "LogicalOperator",
    # Indexes / projections
    "Index",
    "IndexType",
    "Projection",
    # Helpers
    "f",
    "lit",
    "sql",
    "raw",
    "to_expr",
    "array",
    "array_join",
    "cast",
    "coalesce",
    "ifnull",
    "if_",
    "tuple_",
    "map_",
    "over",
    "concat",
    "length",
    "lower",
    "upper",
    "position",
    "substring",
    "replace_all",
    "regex_replace",
    "hash64",
    "round_",
    "abs_",
    "date_add",
    "date_diff",
    "to_date",
    "to_datetime",
    "to_yyyymm",
    "to_yyyymmdd",
    "to_start_of_day",
    "to_start_of_hour",
    "to_start_of_minute",
    "to_start_of_month",
    # DDL builders
    "build_create_database",
    "build_create_dictionary",
    "build_create_materialized_view",
    "build_create_table",
    "build_create_view",
    "build_drop_database",
    "build_drop_table",
    "build_exchange_tables",
    "build_optimize_table",
    "build_rename_table",
    "build_truncate_table",
]
